kind: Deployment
apiVersion: apps/v1
metadata:
  name: dlh-api-test
  labels:
    app: dlh-api-test
    app.kubernetes.io/component: dlh-api-test
    app.kubernetes.io/instance: dlh-api-test
    app.kubernetes.io/name: dlh-api-test
    app.kubernetes.io/part-of: dlh-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlh-api-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dlh-api-test
        deployment: dlh-api-test
    spec:
      containers:
        - name: dlh-api-test
          image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/dlh-api-test:d45f3aa1a6e943589db65aaa3892a7b965c42d70
