apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dlh-api-test
    app.kubernetes.io/component: dlh-api-test
    app.kubernetes.io/instance: dlh-api-test
    app.kubernetes.io/name: dlh-api-test
    app.kubernetes.io/part-of: dlh-api-test
  name: dlh-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlh-api-test
  template:
    metadata:
      labels:
        app: dlh-api-test
        deployment: dlh-api-test
    spec:
      containers:
      - image: goaaroregistry.azurecr.io/024087d6-4aa7-4a52-90ec-0db8ffe1249e/dlh-dev/dlh-api-test:a007b71313c05dc027e1b08326db27ea9519b28d
        name: dlh-api-test
